### ISSUE TITLE
syndie scrapper doesn't have an autolathe

### ISSUE THREAD

**Issue by Addust** [Void-Crew/Voidcrew-LRP#67]
Issue reported from  Round ID: 232 (Voidcrew 2.0)

Reporting client version: 514.1589

why did you even make it syndie

it lacks an autolathe

**Comment by BBBBAface** [comment]
That means its never had an autolathe, huh, didn't think it wouldn't. Kinda crazy if you think about it

**Comment by BBBBAface** [comment]
this should be closed, it definitely has an autolathe

**Comment by NexusLeader** [comment]
This should be closed, it has a autolathe. Check near the cargo consoles.

**Comment by Addust** [comment]
ok
